### ISSUE TITLE
KeyError: 'GT_CLOUD_BASE_URL' when running skatepark emulator example 

### ISSUE THREAD

**Issue by dylanholmes** [griptape-ai/griptape-cli#26]
Running the skatepark emulator example, it seems the example client expects the `GT_CLOUD_BASE_URL` environment variable to be defined, but it's not mentioned in the repo readme. 

```sh
 ❯ poetry run python client.py
Traceback (most recent call last):
  File "/Users/dylan/Documents/managed-structure-example/example-client/client.py", line 26, in <module>
    HOST = os.environ["GT_CLOUD_BASE_URL"]
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 685, in __getitem__
KeyError: 'GT_CLOUD_BASE_URL'
```

I see the example `.env.client.example` contains all the right values, I think it just needs to be mentioned in the readme.

**Comment by SavagePencil** [comment]
check out latest in https://github.com/griptape-ai/griptape-cli/pull/29
