### ISSUE TITLE
Missing `GT_CLOUD_API_KEY` warning with skatepark emulator

### ISSUE THREAD

**Issue by dylanholmes** [griptape-ai/griptape-cli#27]
When running the skatepark emulator example in the readme, running the structure printed the following warning:

```txt
****WARNING****: No value was found for the 'GT_CLOUD_API_KEY' environment variable.
This environment variable is required when running in Griptape Cloud for authorization.
You can generate a Griptape Cloud API Key by visiting https://cloud.griptape.ai/keys .
Specify it as an environment variable when creating a Managed Structure in Griptape Cloud.
```

Does it make sense to print this warning when running against the local emulator (with `GT_CLOUD_BASE_URL` environment variable set to `http://127.0.0.1:5000`)?

**Comment by SavagePencil** [comment]
Yes, that's why it's a warning. This was discovered when we had a working local emulator experience, but when we brought that same .env file and Python code to Griptape Cloud, it failed. It's warning you that there's a disparity between the local emulator and cloud that will be a painful gotcha.
